version: '2'
services:
    meubolso-app:
        image: meubolso
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://meubolso-postgresql:5432/meubolso
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    meubolso-postgresql:
        extends:
            file: postgresql.yml
            service: meubolso-postgresql
